apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: h79vfpms8-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: h79vfpms8-python 
  name: h79vfpms8-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: h79vfpms8-python 
